class Solution {
public:
    char findTheDifference(string s, string t) {
        //t is generated by s
        int n=s.size();
        int m=t.size();
        unordered_map<char,int> mp;
        for(int i=0;i<m;i++){
            mp[t[i]]++;
        }
        for(int j=0;j<n;j++){
            if(mp.find(s[j])!=mp.end()){
                mp[s[j]]--;
                if(mp[s[j]]==0){
                    mp.erase(s[j]);
                }
            }
        }
        return mp.begin()->first;  //it will return the first of remaining mp element
    }
};